[mypy]
python_version = 3.11
files = app/, tests/, training_logic_v2.py, Final_model_v2.py, train_offline.py
warn_unused_configs = True
warn_return_any = False
warn_unused_ignores = True
ignore_missing_imports = True
exclude = (?x)(^Dataset_backup/|^WastageData/|^SaleData_Cleaning/|^kaggle_data/|^kaggle_data_v2/|^catboost_info/|^models/|^backup/|^__pycache__/)

[mypy-training_logic_v2]
ignore_errors = True

[mypy-Final_model_v2]
ignore_errors = True

[mypy-train_offline]
ignore_errors = True
