# SmartSusChef - Mobile Dev Quick Start (Windows PowerShell)
# Launches ML / Backend / (Optional) Frontend
# Backend bound to 0.0.0.0:5001 for Android emulator + physical devices
# Usage:
#   .\dev-start-mobile.ps1
#   START_FRONTEND=false .\dev-start-mobile.ps1   (PowerShell: $env:START_FRONTEND="false")

param(
    [string]$DbServer,
    [int]$DbPort,
    [string]$DbUser,
    [string]$DbPassword,
    [string]$DbName
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
$BackendPort = 5001

# Default: start frontend unless explicitly disabled
if (-not $env:START_FRONTEND) {
    $env:START_FRONTEND = "true"
}

# -- Load .env --------------------------------------------------------------
$envFile = Join-Path $Root ".env"
if (Test-Path $envFile) {
    Write-Host "[OK] Loading config from .env" -ForegroundColor Green
    Get-Content $envFile | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith("#")) {
            $parts = $line -split "=", 2
            if ($parts.Count -eq 2) {
                [System.Environment]::SetEnvironmentVariable(
                    $parts[0].Trim(),
                    $parts[1].Trim(),
                    "Process"
                )
            }
        }
    }
}
else {
    Write-Host "[ERROR] No .env file found. Copy .env.example to .env" -ForegroundColor Red
    exit 1
}

# CLI params override .env
if (-not $DbServer) { $DbServer = $env:DB_SERVER }
if (-not $DbPort) { $DbPort = [int]$env:DB_PORT }
if (-not $DbUser) { $DbUser = $env:DB_USER }
if (-not $DbPassword) { $DbPassword = $env:DB_PASSWORD }
if (-not $DbName) { $DbName = $env:DB_NAME }

Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  SmartSusChef - Mobile Dev Quick Start" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host ""

# -- Detect local Wi-Fi IPv4 ------------------------------------------------
$WifiIP = Get-NetIPAddress `
    -AddressFamily IPv4 `
    -InterfaceAlias "Wi-Fi*" `
    -ErrorAction SilentlyContinue |
Where-Object { $_.IPAddress -notlike "169.254*" } |
Select-Object -First 1 -ExpandProperty IPAddress

if ($WifiIP) {
    Write-Host "[OK] Wi-Fi IP detected: $WifiIP" -ForegroundColor Green
}
else {
    Write-Host "[WARN] Could not detect Wi-Fi IP (physical devices may not connect)" -ForegroundColor Yellow
}

# -- Tool checks ------------------------------------------------------------
$missing = @()
if (-not (Get-Command python -ErrorAction SilentlyContinue)) { $missing += "Python" }
if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) { $missing += ".NET SDK" }
if (-not (Get-Command node -ErrorAction SilentlyContinue)) { $missing += "Node.js" }

if ($missing.Count -gt 0) {
    Write-Host "[ERROR] Missing: $($missing -join ', ')" -ForegroundColor Red
    exit 1
}
Write-Host "[OK] Python / .NET / Node.js installed" -ForegroundColor Green

# -- DB connection string ---------------------------------------------------
$connStr = "Server=$DbServer;Port=$DbPort;Database=$DbName;User Id=$DbUser;Password=$DbPassword;SslMode=None;AllowPublicKeyRetrieval=true;ConnectionTimeout=30"
Write-Host "[OK] DB: $DbServer`:$DbPort/$DbName (user: $DbUser)" -ForegroundColor Green
Write-Host ""

# -- Android local.properties ----------------------------------------------
$AndroidDir = Join-Path $Root "mobile"
$LocalProps = Join-Path $AndroidDir "local.properties"

if (Test-Path $AndroidDir) {
    if (-not (Test-Path $LocalProps)) {
        Write-Host "[INFO] Creating mobile/local.properties" -ForegroundColor Cyan
        @"
## Auto-generated by dev-start-mobile.ps1
## Android Emulator default
local.base.url=http://10.0.2.2:$BackendPort/api/
"@ | Out-File -Encoding utf8 $LocalProps
    }
    elseif (-not (Select-String "^local.base.url=" $LocalProps)) {
        Write-Host "[INFO] Adding local.base.url to existing local.properties" -ForegroundColor Cyan
        "local.base.url=http://10.0.2.2:$BackendPort/api/" | Add-Content $LocalProps
    }
}
else {
    Write-Host "[WARN] mobile/ directory not found, skipping Android config" -ForegroundColor Yellow
}

# -- Start ML ---------------------------------------------------------------
Write-Host "[1/3] Starting ML Service (8000)..." -ForegroundColor Cyan
Start-Process powershell -ArgumentList "-NoExit", "-Command", @"
    `$Host.UI.RawUI.WindowTitle = 'SmartSusChef - ML (8000)'
    Set-Location '$Root\ML'
    python -m pip install -q -r requirements.txt
    python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
"@

Start-Sleep 3

# -- Start Backend (MOBILE) -------------------------------------------------
Write-Host "[2/3] Starting Backend (port $BackendPort)..." -ForegroundColor Cyan
Start-Process powershell -ArgumentList "-NoExit", "-Command", @"
    `$Host.UI.RawUI.WindowTitle = 'SmartSusChef - Backend (Mobile)'
    Set-Location '$Root\backend\SmartSusChef.Api'
    `$env:ASPNETCORE_ENVIRONMENT = 'Development'
    `$env:ConnectionStrings__DefaultConnection = '$connStr'
    `$env:ASPNETCORE_URLS = 'http://0.0.0.0:$BackendPort'
    dotnet run
"@

Start-Sleep 2

# -- Start Frontend (optional) ---------------------------------------------
if ($env:START_FRONTEND -eq "true") {
    Write-Host "[3/3] Starting Frontend (5173)..." -ForegroundColor Cyan
    Start-Process powershell -ArgumentList "-NoExit", "-Command", @"
        `$Host.UI.RawUI.WindowTitle = 'SmartSusChef - Frontend (5173)'
        Set-Location '$Root\frontend'
        npm install --silent
        npm run dev
"@
}
else {
    Write-Host "[3/3] Frontend skipped (mobile-only mode)" -ForegroundColor Yellow
}

# -- Summary ---------------------------------------------------------------
Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  Mobile Dev Environment Ready" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Backend (local)  -> http://localhost:$BackendPort" -ForegroundColor White
Write-Host "  Swagger          -> http://localhost:$BackendPort/swagger" -ForegroundColor White
Write-Host "  ML API           -> http://localhost:8000" -ForegroundColor White
Write-Host ""
Write-Host "  Android Emulator -> http://10.0.2.2:$BackendPort/api/" -ForegroundColor Cyan

Write-Host ""
Write-Host "  Stop services: close each PowerShell window" -ForegroundColor Gray
Write-Host "==========================================" -ForegroundColor Green
