#!/usr/bin/env bash
# SmartSusChef - Mobile Dev Quick Start (macOS / Linux)
# Backend on port 5001 for physical device + emulator

set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"

# -- Load .env file ---------------------------------------------------------
ENV_FILE="$ROOT/.env"
if [ -f "$ENV_FILE" ]; then
    echo "[OK] Loading config from .env"
    set -a
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    set +a
else
    echo "[ERROR] No .env file found. Copy .env.example to .env and fill in your values."
    exit 1
fi

# -- Required env vars ------------------------------------------------------
DB_SERVER="${DB_SERVER:?DB_SERVER not set in .env}"
DB_PORT="${DB_PORT:?DB_PORT not set in .env}"
DB_USER="${DB_USER:?DB_USER not set in .env}"
DB_PASSWORD="${DB_PASSWORD:?DB_PASSWORD not set in .env}"
DB_NAME="${DB_NAME:?DB_NAME not set in .env}"

BACKEND_PORT=5001
START_FRONTEND=${START_FRONTEND:-true}

# -- Detect local Wi-Fi IP (for physical mobile devices) -------------------
WIFI_IP=$(ipconfig getifaddr en0 || true)

if [ -z "$WIFI_IP" ]; then
    echo "[WARN] Could not detect Wi-Fi IP (en0)."
    echo "       Physical devices will NOT be able to reach this machine."
    echo "       Make sure Wi-Fi is on and both devices are on the same network."
else
    echo "[OK] Detected Wi-Fi IP: $WIFI_IP"
fi

echo ""
echo "=========================================="
echo "  SmartSusChef - Mobile Dev Quick Start"
echo "=========================================="
echo ""

echo ""
echo "Mobile API base URLs:"
echo "  Emulator       -> http://10.0.2.2:${BACKEND_PORT}/api/"
if [ -n "$WIFI_IP" ]; then
    echo "  Physical phone -> http://${WIFI_IP}:${BACKEND_PORT}/api/"
else
    echo "  Physical phone -> (Wi-Fi IP not detected)"
fi
echo ""

# -- Android local.properties bootstrap ------------------------------------
ANDROID_DIR="$ROOT/mobile"
LOCAL_PROPS="$ANDROID_DIR/local.properties"

if [ -d "$ANDROID_DIR" ]; then
    if [ ! -f "$LOCAL_PROPS" ]; then
        echo "[INFO] Creating mobile/local.properties (emulator default)"
        cat > "$LOCAL_PROPS" <<EOF
## Auto-generated by dev-start-mobile.sh
## Emulator default
local.base.url=http://10.0.2.2:${BACKEND_PORT}/api/
EOF
    else
        if ! grep -q "^local.base.url=" "$LOCAL_PROPS"; then
            echo "[INFO] Adding local.base.url to existing local.properties"
            echo "local.base.url=http://10.0.2.2:${BACKEND_PORT}/api/" >> "$LOCAL_PROPS"
        fi
    fi
else
    echo "[WARN] Android directory not found, skipping local.properties setup"
fi

# -- Check prerequisites ---------------------------------------------------
MISSING=""
command -v python3 >/dev/null 2>&1 || MISSING="$MISSING Python3"
command -v dotnet  >/dev/null 2>&1 || MISSING="$MISSING .NET-SDK"
command -v node    >/dev/null 2>&1 || MISSING="$MISSING Node.js"

if [ -n "$MISSING" ]; then
    echo "[ERROR] Missing:$MISSING"
    exit 1
fi
echo "[OK] Python / .NET / Node.js installed"

# -- Build connection string ------------------------------------------------
CONN_STR="Server=$DB_SERVER;Port=$DB_PORT;Database=$DB_NAME;User Id=$DB_USER;Password=$DB_PASSWORD;SslMode=None;AllowPublicKeyRetrieval=true;ConnectionTimeout=30"
echo "[OK] DB: $DB_SERVER:$DB_PORT/$DB_NAME (user: $DB_USER)"
export DATABASE_URL="$CONN_STR"
echo ""

# -- Kill existing processes on BACKEND_PORT --------------------------------
echo "[INFO] Checking for processes on port ${BACKEND_PORT}..."
# Find PIDs using the BACKEND_PORT and suppress errors if none are found
PID_ON_PORT=$(lsof -t -i ":${BACKEND_PORT}" || true)
if [ -n "$PID_ON_PORT" ]; then
    echo "[INFO] Killing process(es) $PID_ON_PORT on port ${BACKEND_PORT}."
    # Force kill the process(es)
    kill -9 "$PID_ON_PORT"
    # Give the system a moment to release the port
    sleep 1
else
    echo "[INFO] No process found on port ${BACKEND_PORT}."
fi

# -- Cleanup on exit --------------------------------------------------------
cleanup() {
    echo ""
    echo "Stopping services..."
    [ -n "$ML_PID" ]       && kill "$ML_PID"       2>/dev/null
    [ -n "$BACKEND_PID" ]  && kill "$BACKEND_PID"  2>/dev/null
    [ -n "$FRONTEND_PID" ] && kill "$FRONTEND_PID" 2>/dev/null
    wait 2>/dev/null
    echo "All services stopped."
}
trap cleanup EXIT INT TERM

# -- 1) ML Service ----------------------------------------------------------
echo "[1/3] Starting ML Service (port 8000)..."
(
    cd "$ROOT/ML"
    python3 -m pip install -q -r requirements-prod.txt
    python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
) &
ML_PID=$!
sleep 3

# -- 2) Backend (MOBILE) ----------------------------------------------------
echo "[2/3] Starting Backend (port ${BACKEND_PORT})..."
(
    cd "$ROOT/backend/SmartSusChef.Api"
    export ASPNETCORE_ENVIRONMENT=Development
    export ConnectionStrings__DefaultConnection="$CONN_STR"
    export ASPNETCORE_URLS="http://0.0.0.0:${BACKEND_PORT}"
    dotnet run
) &
BACKEND_PID=$!
sleep 3

# -- 3) Frontend ------------------------------------------------------------
if [ "$START_FRONTEND" = "true" ]; then
    echo "[3/3] Starting Frontend (port 5173)..."
    (
        cd "$ROOT/frontend"
        npm install --silent
        npm run dev
    ) &
    FRONTEND_PID=$!
else
    echo "[3/3] Frontend skipped (mobile-only mode)"
fi

# -- Summary ----------------------------------------------------------------
echo ""
echo "=========================================="
echo "  All Services Started (Mobile Mode)"
echo "=========================================="
echo ""
echo "  Frontend (Web)     -> http://localhost:5173"
echo "  Backend (Local)    -> http://localhost:${BACKEND_PORT}"
echo "  Swagger            -> http://localhost:${BACKEND_PORT}/swagger"
echo "  ML API             -> http://localhost:8000"
echo ""
echo "  Mobile access:"
echo "    Android Emulator -> http://10.0.2.2:${BACKEND_PORT}"
if [ -n "$WIFI_IP" ]; then
    echo "    Physical Device  -> http://$WIFI_IP:${BACKEND_PORT}/api/"
else
    echo "    Physical Device  -> (Wi-Fi IP not detected)"
fi
echo ""
echo "  Press Ctrl+C to stop all services"
echo "=========================================="

wait
