// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSusChef.Api.Data;

#nullable disable

namespace SmartSusChef.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209065225_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartSusChef.Api.Models.ForecastData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PredictedQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("StoreId");

                    b.ToTable("ForecastData");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.GlobalCalendarSignals", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSchoolHoliday")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("RainMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("WeatherDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Date");

                    b.ToTable("GlobalCalendarSignals");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.GlobalIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CarbonFootprint")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GlobalIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CarbonFootprint = 1.10m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2771),
                            IsDefault = true,
                            Name = "Tomato",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2772)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CarbonFootprint = 13.50m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2775),
                            IsDefault = true,
                            Name = "Cheese",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2776)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CarbonFootprint = 0.95m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2779),
                            IsDefault = true,
                            Name = "Flour",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2779)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            CarbonFootprint = 2.70m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2782),
                            IsDefault = true,
                            Name = "Rice",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2783)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            CarbonFootprint = 27.00m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2786),
                            IsDefault = true,
                            Name = "Beef",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2786)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            CarbonFootprint = 12.10m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2789),
                            IsDefault = true,
                            Name = "Pork",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2789)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            CarbonFootprint = 6.90m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2792),
                            IsDefault = true,
                            Name = "Chicken",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2800)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            CarbonFootprint = 0.50m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2803),
                            IsDefault = true,
                            Name = "Lettuce",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2804)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            CarbonFootprint = 0.30m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2807),
                            IsDefault = true,
                            Name = "Potato",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2808)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            CarbonFootprint = 0.70m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2811),
                            IsDefault = true,
                            Name = "Onion",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2812)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000b"),
                            CarbonFootprint = 1.50m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2815),
                            IsDefault = true,
                            Name = "Garlic",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2815)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            CarbonFootprint = 1.80m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2818),
                            IsDefault = true,
                            Name = "Sugar",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2818)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000d"),
                            CarbonFootprint = 11.90m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2822),
                            IsDefault = true,
                            Name = "Butter",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2822)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000e"),
                            CarbonFootprint = 1.90m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2825),
                            IsDefault = true,
                            Name = "Milk",
                            Unit = "L",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2826)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000f"),
                            CarbonFootprint = 0.30m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2829),
                            IsDefault = true,
                            Name = "Egg",
                            Unit = "pcs",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2829)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            CarbonFootprint = 6.00m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2832),
                            IsDefault = true,
                            Name = "Olive Oil",
                            Unit = "L",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2833)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            CarbonFootprint = 2.20m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2851),
                            IsDefault = true,
                            Name = "Soy Sauce",
                            Unit = "L",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2851)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            CarbonFootprint = 0.05m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2855),
                            IsDefault = true,
                            Name = "Salt",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2855)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000013"),
                            CarbonFootprint = 8.00m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2867),
                            IsDefault = true,
                            Name = "Pepper",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2867)
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.HolidayCalendar", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<string>("HolidaysJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CountryCode", "Year");

                    b.ToTable("HolidayCalendars");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CarbonFootprint")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GlobalIngredientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalIngredientId");

                    b.HasIndex("StoreId", "Name")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CarbonFootprint = 1.1m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2139),
                            Name = "Tomato",
                            StoreId = 1,
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2139)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CarbonFootprint = 13.5m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2143),
                            Name = "Cheese",
                            StoreId = 1,
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2144)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CarbonFootprint = 0.9m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2146),
                            Name = "Dough",
                            StoreId = 1,
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2147)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CarbonFootprint = 0.5m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2149),
                            Name = "Lettuce",
                            StoreId = 1,
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2150)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CarbonFootprint = 27.0m,
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2152),
                            Name = "Beef",
                            StoreId = 1,
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2153)
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSubRecipe")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "Name")
                        .IsUnique();

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2314),
                            IsSellable = false,
                            IsSubRecipe = false,
                            Name = "Margherita Pizza",
                            StoreId = 1,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2316)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2318),
                            IsSellable = false,
                            IsSubRecipe = false,
                            Name = "Beef Burger",
                            StoreId = 1,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(2318)
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChildRecipeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChildRecipeId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IngredientId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Quantity = 0.3m,
                            RecipeId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IngredientId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 0.2m,
                            RecipeId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IngredientId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Quantity = 0.15m,
                            RecipeId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            IngredientId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Quantity = 0.2m,
                            RecipeId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            IngredientId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Quantity = 0.05m,
                            RecipeId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            IngredientId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 0.05m,
                            RecipeId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.SalesData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("StoreId", "Date", "RecipeId")
                        .IsUnique();

                    b.ToTable("SalesData");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OutletLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UEN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Smart Sus Chef Corp",
                            ContactNumber = "+65 6000 0000",
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 24, 826, DateTimeKind.Utc).AddTicks(644),
                            IsActive = true,
                            Latitude = 0m,
                            Longitude = 0m,
                            OpeningDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OutletLocation = "123 Orchard Road",
                            StoreName = "Downtown Outlet",
                            UEN = "202400001A",
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 24, 826, DateTimeKind.Utc).AddTicks(646)
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Active");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 24, 982, DateTimeKind.Utc).AddTicks(6576),
                            Email = "",
                            Name = "Administrator",
                            PasswordHash = "$2a$11$ILGJIiRwrLF54nvgfjB0me73ZizNzeRyySZlYkOiKL6v7qKvLIWoe",
                            Role = "Manager",
                            StoreId = 1,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 24, 982, DateTimeKind.Utc).AddTicks(6583),
                            UserStatus = "Active",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(1471),
                            Email = "",
                            Name = "Employee User",
                            PasswordHash = "$2a$11$gJFernJcrgvg.TEo7eA2IONHxA8SChtMBOuWHtZws5rLwdGpdXjNG",
                            Role = "Employee",
                            StoreId = 1,
                            UpdatedAt = new DateTime(2026, 2, 9, 6, 52, 25, 152, DateTimeKind.Utc).AddTicks(1476),
                            UserStatus = "Active",
                            Username = "employee"
                        });
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.WastageData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("StoreId");

                    b.ToTable("WastageData");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.WeatherDaily", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StoreId", "Date");

                    b.ToTable("WeatherDaily");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.ForecastData", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSusChef.Api.Models.Store", "Store")
                        .WithMany("ForecastData")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Ingredient", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.GlobalIngredient", "GlobalIngredient")
                        .WithMany()
                        .HasForeignKey("GlobalIngredientId");

                    b.HasOne("SmartSusChef.Api.Models.Store", "Store")
                        .WithMany("Ingredients")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalIngredient");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Recipe", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Store", "Store")
                        .WithMany("Recipes")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Recipe", "ChildRecipe")
                        .WithMany()
                        .HasForeignKey("ChildRecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartSusChef.Api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartSusChef.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildRecipe");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.SalesData", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Recipe", "Recipe")
                        .WithMany("SalesRecords")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSusChef.Api.Models.Store", "Store")
                        .WithMany("SalesData")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.User", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Store", "Store")
                        .WithMany("Users")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.WastageData", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Ingredient", "Ingredient")
                        .WithMany("WastageRecords")
                        .HasForeignKey("IngredientId");

                    b.HasOne("SmartSusChef.Api.Models.Recipe", "Recipe")
                        .WithMany("WastageRecords")
                        .HasForeignKey("RecipeId");

                    b.HasOne("SmartSusChef.Api.Models.Store", "Store")
                        .WithMany("WastageData")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.WeatherDaily", b =>
                {
                    b.HasOne("SmartSusChef.Api.Models.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("WastageRecords");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("SalesRecords");

                    b.Navigation("WastageRecords");
                });

            modelBuilder.Entity("SmartSusChef.Api.Models.Store", b =>
                {
                    b.Navigation("ForecastData");

                    b.Navigation("Ingredients");

                    b.Navigation("Recipes");

                    b.Navigation("SalesData");

                    b.Navigation("Users");

                    b.Navigation("WastageData");
                });
#pragma warning restore 612, 618
        }
    }
}
