build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexMethod:
    active: true
    threshold: 15
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  TooManyFunctions:
    active: true
    thresholdInFiles: 25
    thresholdInClasses: 25
    thresholdInInterfaces: 25
    thresholdInObjects: 25
    thresholdInEnums: 25

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true

empty-blocks:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable

naming:
  active: true
  FunctionNaming:
    active: true
    excludes: ['**/test/**', '**/androidTest/**']
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
  VariableNaming:
    active: true

performance:
  active: true
  SpreadOperator:
    active: false

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: true
    excludes: ['**/test/**', '**/androidTest/**']
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludeCommentStatements: true
  ReturnCount:
    active: true
    max: 3
    excludeReturnFromLambda: true
  WildcardImport:
    active: true
    excludeImports:
      - 'java.util.*'
      - 'kotlinx.android.synthetic.*'

formatting:
  active: false
  android: true
  autoCorrect: false
